### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by rpsequeira**
Removed sort() so that the order of input is maintained in the output.

### CODE REVIEW

**Comment by icholy** [comment]
If you want this functionality, add a `sort` option which defaults to `true`.

**Comment by rpsequeira** [comment]
Added sort option.

**Comment by rpsequeira** [comment]
When will this version be available in npm?

**Comment by icholy** [comment]
Whoops, I'll do it tomorrow

**Comment by icholy** [comment]
@rpsequeira published

**Pull request merged**
