### PR TITLE
Add 'relative' option

### PR DESCRIPTION
**Pull request by c-martinez**
Added a 'relative' option so that files can be relative to a path other than local file. Useful in combination with 'path' option.

### CODE REVIEW

**Comment by icholy** [comment]
Can you change it to something more descriptive? Maybe `relative_to` or `base_dir`.

**Comment by icholy** [comment]
Actually nvm, it's fine.

**Comment by c-martinez** [comment]
`rel_dir` ? `relative_dir` ?

**Comment by icholy** [comment]
I'd go with `relative_dir`.

**Pull request merged**
